# This is a basic workflow to help you get started with Actions

name: CI Staging Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup GitHub CLI
        uses: actions/setup-go@v2
        with:
          go-version: "^1.15.8" # Ensure compatibility

      - name: Install GitHub CLI
        run: |
          curl -L https://github.com/cli/cli/releases/download/v1.9.2/gh_1.9.2_linux_amd64.deb -o ghcli.deb
          sudo dpkg -i ghcli.deb

      - name: Login to GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      # Runs a set of commands using the runners shell
      - name: Check for existing draft release that starts with 'prod-'
        run: |
          DRAFT_RELEASE_ID=$(gh api repos/${{ github.repository }}/releases --jq '.[] | select( (.draft==true) and (.tag_name | startswith("prod-")) ) | .tag_name' | head -n 1)

          if [ -n "$DRAFT_RELEASE_ID" ]; then
            gh release delete $DRAFT_RELEASE_ID -y
          fi

          RELEASE_TAG="prod-$(date +%Y%m%d%H%M%S)"
          gh release create "$RELEASE_TAG" --draft --title "Prod Draft Release $RELEASE_TAG" --notes "Release notes for $RELEASE_TAG"
